### ISSUE TITLE
Quick start missing in Readme

### ISSUE THREAD

**Issue by kristianmandrup** [benawad/graphql-typescript-stripe-example#1]
Hi Ben,

Would be awesome if you could include a quick Getting started or Install + Run section in the Readme for the most essential steps to get it running locally after a clone. Thanks for all your hard work!
You're the best on the interwebs (Neuromancer?) in the JS/Node space IMO.
Cheers :)

**Comment by kristianmandrup** [comment]
It's a little bit of a hassle to have to go through the full video series and jot down the commands you execute to get it running and then for each branch... Would be great if you could include at least some of the "core" commands in the future, or links to where to register accounts etc.

**Comment by benawad** [comment]
Thanks for the pull request
